### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'unavailable'

### ISSUE THREAD

**Issue by hiatsu0** [PlusPlus-ua/ha_mobilealerts#12]
My MobileAlerts integration started suddenly flooding my log with this error, after upgrading to Home Assistant 2023.5.3 (Supervisor 2023.04.1 - Operating System 10.1). All entities under this integration do not seem to be updating anymore.

These are logged right after system reboot:

```
Logger: homeassistant.components.sensor
Source: custom_components/mobile_alerts/binary_sensor.py:171 
Integration: Sensori (documentation, issues) 
First occurred: 22.02.39 (2 occurrences) 
Last logged: 22.02.39

Error adding entities for domain sensor with platform mobile_alerts
Error while setting up mobile_alerts platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 844, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/mobile_alerts/base.py", line 193, in async_added_to_hass
    self._handle_coordinator_update()
  File "/config/custom_components/mobile_alerts/base.py", line 220, in _handle_coordinator_update
    entity.update_data_from_sensor()
  File "/config/custom_components/mobile_alerts/binary_sensor.py", line 171, in update_data_from_sensor
    (int(time_span_sensor._attr_native_value) == 0) and
ValueError: invalid literal for int() with base 10: 'unavailable'




Logger: aiohttp.server
Source: custom_components/mobile_alerts/binary_sensor.py:171 
Integration: Mobile-Alerts 
First occurred: 22.03.04 (1 occurrences) 
Last logged: 22.03.04

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/mobilealerts/proxy.py", line 87, in request_handler
    await gateway.handle_update(
  File "/usr/local/lib/python3.10/site-packages/mobilealerts/gateway.py", line 526, in handle_update
    await self.handle_sensors_update(packages)
  File "/usr/local/lib/python3.10/site-packages/mobilealerts/gateway.py", line 510, in handle_sensors_update
    await self.handle_sensor_update(
  File "/usr/local/lib/python3.10/site-packages/mobilealerts/gateway.py", line 496, in handle_sensor_update
    await self._handler.sensor_updated(sensor)
  File "/config/custom_components/mobile_alerts/coordinator.py", line 52, in sensor_updated
    self.async_set_updated_data({})
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 376, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/config/custom_components/mobile_alerts/base.py", line 204, in _handle_coordinator_update
    self.update_data_from_sensor()
  File "/config/custom_components/mobile_alerts/binary_sensor.py", line 171, in update_data_from_sensor
    (int(time_span_sensor._attr_native_value) == 0) and
ValueError: invalid literal for int() with base 10: 'unavailable'
```

**Comment by hiatsu0** [comment]
Restoring from a backup back to 2023.4.4 (Supervisor 2023.04.1 - Operating System 10.1) made the sensors update again. No errors in the log. So there must be some breaking change in 2023.5?

**Comment by Iminet72** [comment]
It works for me.
Although I made a few small corrections, they were not included. I will now switch to my modified code

**Comment by hiatsu0** [comment]
Glad to hear. Perhaps this was more general system issue then, although there was very few errors besides this extension. Will try an update again and see how it all goes. Will close for now.
